import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useSession, signIn, signOut } from "next-auth/react";
import NavBar from "../components/Navbar";
import CheckList from "../components/CheckList";

export default function Home() {
  const { data: session } = useSession();
  var item = {
    text: "This is a test",
    isComplete: false,
  };
  var items = [item, item, item, item, item, item, item, item, item, item];
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <NavBar session={session} />
        <CheckList items={items} />
      </main>
    </div>
  );
}
