import Head from "next/head";
import { getSession, useSession } from "next-auth/react";
import NavBar from "/components/Navbar";
import CheckList from "/components/CheckList";
import { Container, Row } from "react-bootstrap";
import { useEffect, useState } from "react";
import prisma from "/prisma/client";

import styles from "/styles/Home.module.css";

// load todos server side
export async function getServerSideProps(context) {
  const session = await getSession(context);
  const email = session ? session.user.email : "public@dinh.cc";

  const todos = JSON.parse(
    JSON.stringify(
      await prisma.todo.findMany({
        where: {
          user: {
            email: email,
          },
        },
      })
    )
  );

  return { props: { todos } };
}

export default function Home({ todos }) {
  const { data: session } = useSession();
  const [todosState, setTodosState] = useState(todos);

  useEffect(() => {}, [todosState]);

  async function addTodo() {
    const newTodoObj = {
      title: "New Task",
      description: "",
      completed: false,
      email: session?.user.email,
    };
    const response = await fetch("/api/todos", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(newTodoObj),
    });
    const TodoFromServer = await response.json();

    setTodosState([...todosState, TodoFromServer]);
  }
  return (
    <>
      <Head>
        <title>Checkbox</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Container className="d-flex flex-column">
          <NavBar session={session} />
          <CheckList items={todosState} session={session} />
          <Row className="whitespace" onClick={addTodo} />
        </Container>
      </main>
    </>
  );
}
